name: Update Nix expression
on:
  schedule:
  - cron: '0 0 * * *'
  push:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out the master branch of our repo
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Nix
      uses: cachix/install-nix-action@v6
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install nox
      run: |
        python3.7 -m pip install nox
    - name: Generate Nix expression from PyPI package
      run: |
        nox -f instawow/noxfile.py -s nixify -- ..
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v2.4.0
      with:
        commit_message: Update
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
