name: Update Nix expression
on:
  schedule:
  - cron: '0 0 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Check-out the master branch
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure git
      run: |
        git config user.email 'layday@protonmail.com'
        git config user.name  'layday-on-the-cloud'
    - name: Install Nix
      uses: cachix/install-nix-action@v6
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install nox
      run: |
        python3.7 -m pip install nox
    - name: Generate Nix expression from PyPI package
      run: |
        nox -f instawow/noxfile.py -s nixify -- ..
    - name: Check if the requirements have changed
      run: |
        git diff --exit-code || echo '::set-env name=HAS_CHANGES::1'
    - name: Commit changes
      if: env.HAS_CHANGES
      run: |
        git commit -a -m 'Update'
    - name: Push changes to master
      if: env.HAS_CHANGES
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
